import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import sideImg from '../public/reading.png'

function about() {
  return (
    <div className="h-screen">
      <Head>
        <title>My Uni Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className="px-1 grid grid-col-1 lg:grid-cols-2 gap-10 lg:gap-40 bg-[#F9FAFB] py-10">
          <div className="">
            {/* <p>Image section</p> */}
          <Image
            src={sideImg}
            alt="Picture of the author"
            width={900}
            height={700}
            className="rounded-md object-fit"
          />
          </div>
          <div className="flex flex-col space-y-2 py-16">
            <h1 className="text-[#103A5C] text-xl font-bold">
              ABOUT
            </h1>

            <h1 className="text-black text-2xl font-bold mb-8">
              MyUniWork
            </h1>
            
              <p className="text-md pb-8">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestias aut, repellat 
                  ipsum facere voluptate dicta obcaecati deserunt nobis suscipit eaque?
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestias aut, repellat 
                  ipsum facere voluptate dicta obcaecati deserunt nobis suscipit eaque?
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestias aut, repellat 
                  ipsum facere voluptate dicta obcaecati deserunt nobis suscipit eaque?
              </p>  

              <p>
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestias aut, repellat 
                  ipsum facere voluptate dicta obcaecati deserunt nobis suscipit eaque?
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestias aut, repellat 
                  ipsum facere voluptate dicta obcaecati deserunt nobis suscipit eaque?
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestias aut, repellat 
                  ipsum facere voluptate dicta obcaecati deserunt nobis suscipit eaque?
              </p>  

              <p>
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit. Molestias aut, repellat 
                  ipsum facere voluptate dicta obcaecati deserunt nobis suscipit eaque?
              </p>  
            
          </div>
          
      </div>

      {/* Most chosen modules section */}

        
      
      <Footer />
    </div>
  )
}

export default about
