import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

function help() {
  return (
    <div className="h-screen">
      <Head>
        <title>My Uni Work | Help </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="home">
          <div className="welcome-text">
          </div>
      </div>

      <div className=" lg:px-32 px-4 grid grid-col-1 lg:grid-cols-2 gap-2 lg:gap-4 bg-[#F9FAFB] py-10">
          <div className="flex flex-1 w-42 flex-col space-y-5">
            <h1 className="text-[#000] text-3xl font-bold">
              Frequently Asked Questions
            </h1> 
            <p className="text-base text-[#333]">Can't find the answer you're looking for? Contact us on <a className="font-semibold text-[#103A5C]" href="mailto:myuniwork22@gmail.com">myuniwork22@gmail.com</a></p>
          
                
       
          </div>
          <div className="flex-1 w-full py-10">
          <div className="flex items-center mb-4">
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-lg font-semibold">Is MyUniWork available for other institutions?</h1>
                    <p className="text-sm">
                      MyUniWork was built by a Nelson Mandela Universty student for their honours project and thus is currently available
                      for use at Nelson Mandela University only.
                    </p>
                </div>
                
          </div>
           
            <div className="flex items-center mb-4">
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-lg font-semibold">Is MyUniWork used by undergraduates?</h1>
                    <p className="text-sm">
                      MyUniWork is currently available for prospective honours students in the Computing Science department only.
                    </p>
                    </div>
                
            </div>

      
          </div>
      </div>

      <Footer />
    </div>
  )
}

export default help
