import Head from 'next/head'
import Image from 'next/image'
import welcomeImg from "../public/welcome.png";
import homeImg from '../public/home.png';
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import MenuIcon from '@heroicons/react/solid'
// import readingImg from '../public/reading.png'
import { BookOpenIcon } from '@heroicons/react/solid';
import { modalState } from '../atoms/modalAtom';
import { useRecoilState } from 'recoil';
import { useRouter } from 'next/router';


export default function Home() {

  const [isOpen, setIsOpen] = useRecoilState(modalState); 
  const router = useRouter();

  return (
    <div className="h-screen">
      <Head>
        <title>My Uni Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="home">
          <div className="welcome-text">
          </div>
      </div>

      <div className=" lg:px-24 px-4 grid grid-col-1 lg:grid-cols-2 gap-10 lg:gap-4 bg-[#F9FAFB] py-10">
          <div className="flex flex-col space-y-5">
            <h1 className="text-[#000] text-3xl font-bold">
              Choosing Honours Modules Made Easier
            </h1>
            <div className="flex items-center">
                <div>
                    {/* <BookOpenIcon className="w-9 h-9 text-[#F9B42A]"/>
                    <Image src={readingImg} width={70} height={70} className="rounded"/> */}
                </div>
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-2xl font-bold">Learn more about modules offered</h1>
                    <p className="text-md">
                      A list of all modules offered at honours has been collected. Read more about the modules
                      and see which would best suit your schedule.
                    </p>
                </div>

            </div>
            <div className="flex items-center">
                <div>
                    {/* <BookOpenIcon className="w-9 h-9 text-[#F9B42A]"/>
                    <Image src={readingImg} width={70} height={70} className="rounded"/> */}
                </div>
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-2xl font-bold">Add modules to your schedule</h1>
                    <p className="text-md">
                      Select and add the modules you wish to register for to your own personalised schedule from the list 
                      of elective modules given to you.
                    </p>
                </div>
                
            </div>
            <div className="flex items-center">
                <div>
                    {/* <BookOpenIcon className="w-9 h-9 text-[#F9B42A]"/>
                    <Image src={readingImg} width={70} height={70} className="rounded"/> */}
                </div>
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-2xl font-bold">Workload schedule</h1>
                    <p className="text-md">
                      View the workload schedule of all modules offered to determine the impact a particular selection of modules
                       will have on your work schedule.
                    </p>
                </div>
                
            </div>
            <div className="flex items-center">
                <div>
                    {/* <BookOpenIcon className="w-9 h-9 text-[#F9B42A]"/>
                    <Image src={readingImg} width={70} height={70} className="rounded"/> */}
                </div>
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-2xl font-bold">Personalised workload schedule</h1>
                    <p className="text-md">
                      A personalised workload schedule is created for you from the modules you have selected with mandatory
                      modules already selected for you.
                    </p>
                </div>
                
            </div>
          </div>
          <div className="">
            {/* <p>Image section</p> */}
          <Image
            src={homeImg}
            alt="Picture of the author"
            width={900}
            height={900}
            className="rounded-lg"
            object-cover
          />
          </div>
      </div>

      {/* Most chosen modules section */}

        
      
      <Footer />
    </div>
  )
}
