import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import img from '../../logosamples/1.JPG' 
import welcomeImg from "../public/welcome.png";
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import MenuIcon from '@heroicons/react/solid'
import readingImg from '../public/reading.png'
import { BookOpenIcon } from '@heroicons/react/solid';
import { modalState } from '../atoms/modalAtom';
import { useRecoilState } from 'recoil';


export default function Home() {

  const [isOpen, setIsOpen] = useRecoilState(modalState); 

  return (
    <div className="h-screen">
      <Head>
        <title>My Uni Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="home">
          <div className="welcome-text">
          </div>
      </div>

      <div className=" lg:px-44 px-4 grid grid-col-1 lg:grid-cols-2 gap-10 lg:gap-40 bg-[#F9FAFB] py-10">
          <div className="flex flex-col space-y-5">
            <h1 className="text-[#000] text-3xl font-bold">
              Choosing honours modules made easier.
            </h1>
            <div className="flex items-center">
                <div>
                    {/* <BookOpenIcon className="w-9 h-9 text-[#F9B42A]"/>
                    <Image src={readingImg} width={70} height={70} className="rounded"/> */}
                </div>
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-2xl font-bold">Learn more about modules offered</h1>
                    <p className="text-md">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Eos cumque quod nostrum sed quisquam repellat quae eius dicta! Consectetur, ad?
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, rem.
                    </p>
                </div>

            </div>
            <div className="flex items-center">
                <div>
                    {/* <BookOpenIcon className="w-9 h-9 text-[#F9B42A]"/>
                    <Image src={readingImg} width={70} height={70} className="rounded"/> */}
                </div>
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-2xl font-bold">Add modules to your schedule</h1>
                    <p className="text-md">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Eos cumque quod nostrum sed quisquam repellat quae eius dicta! Consectetur, ad?
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, rem.
                    </p>
                </div>
                
            </div>
            <div className="flex items-center">
                <div>
                    {/* <BookOpenIcon className="w-9 h-9 text-[#F9B42A]"/>
                    <Image src={readingImg} width={70} height={70} className="rounded"/> */}
                </div>
                <div className="flex flex-col space-y-2">
                    <h1 className="text-[#333] text-2xl font-bold">View work schedule</h1>
                    <p className="text-md">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit.
                      Eos cumque quod nostrum sed quisquam repellat quae eius dicta! Consectetur, ad?
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit, rem.
                    </p>
                </div>
                
            </div>
          </div>
          <div className="">
             Image Section
          </div>
      </div>

      {/* Most chosen modules section */}

        
      
      {/* <Footer /> */}
    </div>
  )
}
