import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import img from '../../../logosamples/1.JPG' 
import welcomeImg from "../../public/welcome.png";
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import MenuIcon from '@heroicons/react/solid'
import readingImg from '../../public/reading.png'
import { BookOpenIcon } from '@heroicons/react/solid';
import Link from 'next/link';
import Lecturer from '../../components/Lecturer';
import { useRecoilState } from 'recoil';
import { addLecturer, modalState } from '../../atoms/modalAtom';
import MyModal from '../../components/Modal';
import DashboardSidebar from '../../components/DashboardSidebar';


export default function lecturers() {
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  const [isAddLecturer, setIsAddLecturer] = useRecoilState(addLecturer);

  return (
    <div className="h-screen">
      <Head>
        <title>My Uni Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="lg:flex space-x-0 h-full">
          {/* sidebar area  */}
          <DashboardSidebar lecturers/>

          {/* content area */}
          <div className="px-6 flex flex-col gap-2 m-4 w-full">
          <div className="lg:flex m-2 items-center justify-between">
              <p className="text-lg lg:text-2xl m-2 font-semibold text-[#333]">
                  Honours Lecturers     
              </p>
                <div className="flex flex-col lg:flex-row lg:items-center justify-end gap-1">
                  <button className="bg-[#103A5C] text-white font-semibold p-3 rounded-md hover:opacity-90
                      " onClick={(e) =>{
                        setIsOpen(true);
                        setIsAddLecturer(true);
                      }} >
                      Add Lecturer
                  </button> 
                
                  
                 </div>
            </div>
            <Lecturer />
            <Lecturer />
            <Lecturer />
            <Lecturer />
            <Lecturer />
          </div>
      </div>
        
         {/* Modal */}
      {isOpen && <MyModal/>}

      {/* <Footer /> */}
    </div>
  )
}
