import Head from 'next/head'
import React from 'react'
import DashboardSidebar from '../../components/DashboardSidebar'
import MyModal from '../../components/Modal'
import Navbar from '../../components/Navbar'

function recommendations() {
  return (
    <div className="h-screen">
    <Head>
      <title>My Uni Work</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Navbar />
    <div className="lg:flex space-x-0 h-full">
        {/* sidebar area  */}
        <DashboardSidebar recommendations/>

        {/* content area */}
        <div className="px-6 flex flex-col gap-2 m-4 w-full">
        <div className="lg:flex m-2 items-center justify-between">
            <p className="text-lg lg:text-2xl m-2 font-semibold text-[#333]">
                Module Selection recommendations     
            </p>
   
          </div>
          
        </div>
    </div>
      
       {/* Modal */}
    {/* {isOpen && <MyModal/>} */}

    {/* <Footer /> */}
  </div>
  )
}

export default recommendations
