import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import img from '../../../logosamples/1.JPG' 
import welcomeImg from "../../public/welcome.png";
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import MenuIcon from '@heroicons/react/solid'
import readingImg from '../../public/reading.png'
import { BookOpenIcon } from '@heroicons/react/solid';
import Link from 'next/link';
import Week from '../../components/Week';
import DashboardSidebar from '../../components/DashboardSidebar';


export default function schedule() {
  return (
    <div className="h-full">
      <Head>
        <title>My Uni Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="lg:flex space-x-0 h-full">
          {/* sidebar area  */}
          <DashboardSidebar schedule />

          {/* content area */}
          <div className="flex flex-col lg:px-10 mt-4 space-y-2 mb-6 w-full">
            <div className="lg:flex m-2 items-center justify-between">
              <p className="text-lg lg:text-2xl m-2 font-semibold text-[#333]">
                  Provisional Workload Schedule   
              </p>
                
            </div>
            
            <div className="flex flex-col gap-4">
              <Week />
              <Week />
              <Week />
              <Week />
            </div>
          
          </div>
      </div>
        

      {/* <Footer /> */}
    </div>
  )
}
