import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import img from '../../../logosamples/1.JPG' 
import welcomeImg from "../../public/welcome.png";
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import MenuIcon from '@heroicons/react/solid'
import readingImg from '../../public/reading.png'
import { BookOpenIcon } from '@heroicons/react/solid';
import Link from 'next/link';


export default function schedule() {
  return (
    <div className="h-screen">
      <Head>
        <title>My Uni Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="flex">
          {/* sidebar area  */}
          <div className="bg-[#F9FAFB] p-3 h-screen w-72 flex flex-col">
            <Link href="/dashboard/schedule" >
                  <a className="text-lg p-2 rounded-sm bg-white font-semibold">
                      Workload schedule
                  </a>
            </Link>

            <Link href="/dashboard/modules" >
                  <a className="text-lg p-2 rounded-sm font-semibold">
                      Selected Modules
                  </a>
            </Link>
          </div>

          {/* content area */}
      </div>
        

      {/* <Footer /> */}
    </div>
  )
}
