import { doc, onSnapshot, query } from 'firebase/firestore';
import Head from 'next/head'
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'
import { useRecoilState } from 'recoil';
import { modalState } from '../../atoms/modalAtom';
import Module from '../../components/module/Module';
import Navbar from '../../components/Navbar'
import { db } from '../../firebase';
import Footer from '../../components/Footer';

function modulePage() {
    const [isOpen, setIsOpen] = useRecoilState(modalState);
    const [module, setModule] = useState("");
    const router = useRouter();
    const {id} = router.query; 

    useEffect(
        () =>
          onSnapshot(query(doc(db, "modules", id)), (snapshot) => {
            setModule(snapshot.data());
          }),
        [db]
    );


  return (
    <div className="lg:h-full">
      <Head>
        <title>My Uni Work | Module</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Module key={id} module={module} modulePage/>

      <Footer />

    </div>
  )
}

export default modulePage
