import { doc, onSnapshot, query, collection, orderBy } from 'firebase/firestore';
import Head from 'next/head'
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'
import { useRecoilState } from 'recoil';
import { modalState, addAssessment } from '../../atoms/modalAtom';
import Module from '../../components/module/Module';
import Navbar from '../../components/Navbar'
import { db } from '../../firebase';
import Footer from '../../components/Footer';
import Assessment from './../../components/assessment/Assessment';
import MyModal from '../../components/Modal';

function modulePage() {
    const [isOpen, setIsOpen] = useRecoilState(modalState);
    const [isAddAssessment, setIsAddAssessment] = useRecoilState(addAssessment);
    const [module, setModule] = useState("");
    const [assessments, setAssessments] = useState(null);
    const router = useRouter();
    const {id} = router.query; 

    useEffect(
        () =>
          onSnapshot(query(doc(db, "modules", id)), (snapshot) => {
            setModule(snapshot.data());
          }),
        [db]
    );
    
    useEffect(
      () =>  onSnapshot(
        query(collection(db, "modules", id, "assessments"), orderBy("submissionWeek")),
        (snapshot) => {
        setAssessments(snapshot.docs);    
        }
    ),
    [db]
    )


  return (
    <div className="lg:h-full">
      <Head>
        <title>My Uni Work | Module</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className=" flex flex-col">
        <div className="">
           <Module key={id} module={module} modulePage/></div>
         
         <div className=' px-4 md:px-40 lg:px-80 lg:py-8'> 
            <h1 className='text-[#333] font-semibold mb-3 text-3xl text-center'>Assessments</h1>
            <div className="flex flex-col gap-4">
              {assessments?.map(assessment => (
                <Assessment moduleId={id} Id={assessment.id} key={assessment.id} assessment={assessment.data()} modulePage/>
              ))}
            </div>
            
        </div>
      </div>

      {isOpen && <MyModal module={module}/>}

      <Footer />

    </div>
  )
}

export default modulePage
