import Head from 'next/head'
import Image from 'next/image'
// import styles from '../../styles/Home.module.css'
import img from '../../../logosamples/1.JPG' 
import welcomeImg from "../../public/welcome.png";
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import MenuIcon, { SearchIcon } from '@heroicons/react/solid'
import readingImg from '../../public/reading.png'
import { BookOpenIcon } from '@heroicons/react/solid';
import Module from '../../components/Module';
import Link from 'next/link';


export default function Modules() {
  return (
    <div className="h-screen">
      <Head>
        <title>My Uni Work | Modules</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      {/* <div className="home">
          <div className="welcome-text">
          </div>
      </div> */}

      {/* Heading and filter options section */}
      <div className="mt-8 lg:px-24 px-2 flex flex-col lg:flex-row lg:items-center justify-between space-y-3">
          {/* Page heading */}
        <p className="text-lg lg:text-2xl font-semibold text-[#333]">
           Browse honours modules offered.     
        </p>
        {/* Search modulese section */}
        <div className="max-w-xs border rounded-md">
            <div className="relative p-0 rounded-md w-full">
                <div className="absolute inset-y-0 pl-3 flex items-center pointer-events-none">
                  <SearchIcon className="h-6 w-6 text-gray-500" />
                </div>
                <input 
                  className="bg-[#F9FAFB] p-3 block w-full pl-10 sm:text-sm 
                      border-gray-300 focus:ring-black 
                      focus:border-black rounded-md shadow-sm" 
                      type="text"
                      placeholder="Search Module"/>
              </div>
         </div>

         {/* Buttons */}
        <div className="flex items-center">
            <button className="bg-[#103A5C] text-white font-semibold p-3 rounded-md hover:opacity-90">
                Add Module
            </button>            
        </div>

      </div>
      
      {/* Modules list */}
      <div className="flex flex-col lg:px-24 px-2 mt-4 space-y-2 mb-6">
        <Module />
        <Module />
        <Module />
        <Module />
        <Module />

      </div>
     
      
      {/* <Footer /> */}
    </div>
  )
}
