import { doc, onSnapshot, query } from 'firebase/firestore';
import Head from 'next/head'
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'
import { useRecoilState } from 'recoil';
import { modalState } from '../../../atoms/modalAtom';
import Lecturer from '../../../components/lecturer/Lecturer'
import MyModal from '../../../components/Modal';
import Navbar from '../../../components/Navbar'
import { db } from '../../../firebase';

function lecturerPage() {
    const [isOpen, setIsOpen] = useRecoilState(modalState);
    const [lecturer, setLecturer] = useState("");
    const router = useRouter();
    const {id} = router.query;

    useEffect(
        () =>
          onSnapshot(query(doc(db, "lecturers", id)), (snapshot) => {
            setLecturer(snapshot.data());
          }),
        [db]
    );


  return (
    <div className="h-full">
      <Head>
        <title>My Uni Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Lecturer id={id} key={id} lecturer={lecturer} lecturerPage/>

      {/* Modal */}
      {isOpen && <MyModal lecturerId={id} lecturer={lecturer}/>}

    </div>
  )
}

export default lecturerPage
