import Head from 'next/head'
import Navbar from '../../../components/Navbar'
import Footer from '../../../components/Footer'
import Lecturer from '../../../components/Lecturer';
import { useRecoilState } from 'recoil';
import { addLecturer, modalState } from '../../../atoms/modalAtom';
import MyModal from '../../../components/Modal';
import DashboardSidebar from '../../../components/DashboardSidebar';
import { useEffect, useState } from 'react';
import { collection, onSnapshot, query } from 'firebase/firestore';
import { db } from '../../../firebase';
import { useUserAuth } from '../../../context/UserAuthContext';
import { useRouter } from 'next/router';


export default function lecturers({id}) {
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  const [isAddLecturer, setIsAddLecturer] = useRecoilState(addLecturer);
  const [lecturers, setLecturers] = useState([]);
  const {userInfo} = useUserAuth();
  const router = useRouter();

  useEffect( 
    () =>
    onSnapshot(
      query(collection(db, 'lecturers')),
      (snapshot) => {
        setLecturers(snapshot.docs);
      }
    ),
    [db]
  );


  return (
    <div className="lg:h-full">
      <Head>
        <title>My Uni Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className="lg:flex space-x-0 h-full">
          {/* sidebar area  */}
          <div>
            <DashboardSidebar lecturers/>
          </div>
          

          {/* content area */}
          <div className="px-6 flex flex-col gap-2 m-4 w-full">
          <div className="lg:flex m-2 items-center justify-between">
              <p className="text-lg lg:text-2xl m-2 font-semibold text-[#333]">
                  Honours Lecturers     
              </p>

                {userInfo?.isAdmin && (
                  <div className="flex flex-col lg:flex-row lg:items-center justify-end gap-1">
                    <button className="bg-[#103A5C] text-white font-semibold p-3 rounded-md hover:opacity-90
                        " onClick={(e) =>{
                          setIsOpen(true);
                          setIsAddLecturer(true);
                        }} >
                        Add Lecturer
                    </button>  
                  </div>
                )}
     
            </div>
            <div className="flex flex-col">
                {lecturers.map(lecturer =>(
                  <Lecturer id={lecturer.id} key={id} lecturer={lecturer.data()}/>
                ))}
        
            </div>
          </div>
      </div>
        
         {/* Modal */}
      {isOpen && <MyModal/>}

      {/* <Footer /> */}
    </div>
  )
}
